---

- name: Install requirements
  apt:
    name: letsencrypt
    state: present

- name: Generate certificates
  shell: "systemctl stop nginx && /usr/bin/certbot certonly --agree-tos --email webmaster@{{ observium_domain }} --domains {{ observium_domain }} --standalone"
  args:
    creates: "/etc/letsencrypt/renewal/{{ observium_domain }}.conf"
  notify: restart nginx

- name: Configure certificate renewal service
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  with_items:
    - letsencrypt.service
    - letsencrypt.timer
  notify:
    - restart letsencrypt timer

- name: Start and enable certificate renewal timer
  systemd:
    name: letsencrypt.timer
    enabled: yes
    state: started
