---

- name: Install requirements
  apt:
    name: letsencrypt
    state: present

- name: Generate certificates
  command: /usr/bin/certbot/certonly --agree-tos --email webmaster@{{ ansible_domain }} --domains {{ ansible_nodename }}
  args:
    creates: /etc/letsencrypt/renewal/{{ ansible_nodename }}.conf

- name: Configure certificate renewal service
  template: src={{ item }}.j2 dest=/etc/systemd/system/{{ item }}
  with_items:
    - letsencrypt.service
    - letsencrypt.timer
  notify:
    - restart letsencrypt timer

- name: Start and enable certificate renewal timer
  systemd:
    name: letsencrypt.timer
    enabled: yes
    state: started
