---

- name: Install requirements
  apt:
    name: python3-mysqldb
    update_cache: yes
    state: present

- name: Install package
  apt:
    name: mariadb-server
    state: present
  notify: restart mariadb service

- name: Configure service
  template:
    src: mysql.cnf.j2
    dest: /etc/mysql/conf.d/mysql.cnf
  notify: restart mariadb service

- name: Install mysqlcheck service
  copy:
    src: mysqlcheck.service
    dest: /etc/systemd/system/
  notify:
    - restart mysqlcheck service

- name: Install mysqlcheck timer
  copy:
    src: mysqlcheck.timer
    dest: /etc/systemd/system/
  notify:
    - restart mysqlcheck service

- name: Start and enable mysqlcheck timer
  systemd:
    name: mysqlcheck.timer
    state: started
    enabled: yes

- name: Start and enable mariadb service
  systemd:
    name: mariadb.service
    state: started
    enabled: yes
