---

- name: Install package
  apt:
    name: nginx
    state: present

- name: Configure service
  template:
    src: nginx.conf.j2
    dest: /etc/nginx.conf
  notify: restart nginx service

- name: Create configuration directory
  file:
    dest: /etc/nginx/conf.d
    state: directory

- name: Create site directory
  file:
    dest: /etc/nginx/sites-enabled
    state: directory

- name: Configure service
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx service

- name: Configure HTTPS
  template:
    src: https.conf.j2
    dest: /etc/nginx/conf.d/https.conf
  notify: restart nginx service

- name: Configure PHP
  template:
    src: php.conf.j2
    dest: /etc/nginx/conf.d/php.conf
  notify: restart nginx service

- name: Start and enable service
  systemd:
    name: nginx.service
    state: started
    enabled: yes
