---

- name: Install Nginx package
  apt:
    name: nginx
    state: present

- name: Configure Nginx service
  template:
    src: nginx.conf.j2
    dest: /etc/nginx.conf
  notify: restart nginx service

- name: Create Nginx configuration directory
  file:
    dest: /etc/nginx/conf.d
    state: directory

- name: Create Nginx site directory
  file:
    dest: /etc/nginx/sites-enabled
    state: directory

- name: Configure Nginx service
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx service

- name: Configure Nginx HTTPS parameters
  template:
    src: https.conf.j2
    dest: /etc/nginx/conf.d/https.conf
  notify: restart nginx service

- name: Configure Nginx PHP parameters
  template:
    src: php.conf.j2
    dest: /etc/nginx/conf.d/php.conf
  notify: restart nginx service

- name: Start and enable Nginx service
  systemd:
    name: nginx.service
    state: started
    enabled: yes
