---
- name: Install rrdcached packages
  apt:
    name:
      - rrdtool
      - rrdcached
    state: present
  notify: restart rrdcached service

- name: Create rrdcached system group
  group:
    name: rrd
    system: yes
    state: present

- name: Create rrdcached data directories
  file:
    dest: "{{ item }}"
    state: directory
    group: rrd
    mode: '0775'
  with_items:
    - "{{ observium_cache_dir }}/rrd"
    - "{{ observium_cache_dir }}/journal"

- name: Configure rrdcached service
  template:
    src: rrdcached.service.j2
    dest: /etc/systemd/system/rrdcached.service
  notify: restart rrdcached service

- name: Start and enable rrdcached service
  systemd:
    name: rrdcached.service
    state: started
    enabled: yes
