---
- name: Install packages
  apt:
    name:
      - rrdtool
      - rrdcached
    state: present
  notify: restart rrdcached

- name: Create system group
  group:
    name: rrd
    system: yes
    state: present

- name: Create data directories
  file:
    dest: "{{ item }}"
    state: directory
    group: rrd
  with_items:
    - "{{ observium_cache_dir }}/rrd"
    - "{{ observium_cache_dir }}/journal"

- name: Configure service
  template:
    src: rrdcached.service.j2
    dest: /etc/systemd/system/rrdcached.service
  notify: restart rrdcached

- name: Enable service
  service:
    name: rrdcached
    state: started
    enabled: yes
