---

- name: restart mariadb service
  systemd:
    name: mariadb.service
    state: restarted

- name: restart nginx service
  systemd:
    name: nginx.service
    state: restarted

- name: restart php-fpm service
  systemd:
    name: php7.4-fpm.service
    state: reloaded

- name: restart rrdcached service
  systemd:
    name: rrdcached.service
    state: restarted

- name: restart mysqlcheck service
  systemd:
    name: mysqlcheck.timer
    state: restarted
    daemon_reload: yes

- name: update observium
  command: ./discovery.php -u
  args:
    chdir: /opt/observium
  become_user: www-data

- name: restart letsencrypt timer
  systemd:
    name: letsencrypt.timer
    state: restarted
    daemon_reload: yes

- name: restart syslog-ng service
  systemd:
    name: syslog-ng.service
    state: restarted
